from .day_01 import *
from .day_02 import *
from .day_03 import *
from .day_04 import *
from .day_05 import *
from .day_06 import *
from .day_07 import *
from .day_08 import *
from .day_09 import *
from .day_10 import *
from .day_11 import *
from .day_12 import *
from .day_13 import *
from .day_14 import *
from .day_15 import *
from .day_16 import *
from .day_17 import *
from .day_18 import *
from .day_19 import *
from .day_20 import *
from .day_21 import *
from .day_22 import *
from .day_23 import *
from .day_24 import *
from .day_25 import *
